# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n' : '@stable'
    'frameworks/karchive' : '@stable'
    'frameworks/kcrash' : '@stable'
    'frameworks/solid' : '@stable'
    'frameworks/kio' : '@stable'
