# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n' : '@latest-kf6'
    'frameworks/karchive' : '@latest-kf6'
    'frameworks/kcrash' : '@latest-kf6'
    'frameworks/solid' : '@latest-kf6'
    'frameworks/kio' : '@latest-kf6'

Options:
  require-passing-tests-on: ['Linux']
  enable-lsan: True
